[package]
name = "hello-rust"
version = "0.1.0"
authors = ["proartmateur <ennimandroid@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
notify = "4.0.0"
chrono = "0.4"
human-size = "0.4.1"